apiVersion: v1
kind: Service
metadata:
  name: okk7
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "okk7"
    port: 8080
  selector:
    app: okk7
